trigger:
- master

variables:
  CI: true

pool:
  vmImage: macOS-10.13

steps:
- script: |
    brew list
    # Azure already has brew installed, and we need to
    # unlink the existing node package first before we run setup
    brew unlink node@6
    ./boot/init.sh

# Install dependencies
- script: |
    # Remove cask entries first
    cat Brewfile | grep -vE "cask " > Brewfile.alt
    mv Brewfile.alt Brewfile
    brew bundle

# Run linting
- script: make check

# Run dotfile linking
- script: pipenv install
- script: pipenv run ./cli.py link
- script: pipenv run ./cli.py unlink
- script: pipenv run ./cli.py link
- script: ./scripts/sync.sh --force
