tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
brew "awscli"
brew "bind"
brew "cask"
brew "dnsmasq", restart_service: true
brew "fish"
brew "fontconfig"
brew "git"
brew "gradle"
brew "hugo"
brew "pipenv"
brew "shellcheck"
brew "stow"
brew "terraform"
brew "tmux"
brew "vim"
brew "watchman"
brew "yarn", args: ["without-node"]
cask "android-ndk"
cask "android-sdk"
cask "fastlane"
cask "java8"
