# Prospector profile
# https://github.com/PyCQA/prospector/blob/master/prospector/profiles/profiles/default.yaml

strictness: high
doc-warnings: false
test-warnings: false
autodetect: true
member-warnings: false
