name: Continuous Integration

on: [push]

jobs:
  test:
    runs-on: macos-10.14
    env:
      CI: true
    steps:
      - uses: actions/checkout@v1
      - name: 
        run: make check || true
  build:
    runs-on: macos-10.14
    env:
      CI: true
    steps:
      - uses: actions/checkout@v1
      - name: Run setup 
        run: |
          brew list
          ./boot/init.sh
      - name: Test linking and syncing
        run: ./scripts/sync.sh --force
