name: Continuous Integration

on: [push]

jobs:
  test:
    runs-on: macos-10.14
    env:
      CI: true
    steps:
      - uses: actions/checkout@v1
      - run: make check || true
  build:
    runs-on: macos-10.14
    env:
      CI: true
    steps:
      - uses: actions/checkout@v1
      - run: brew list
      - run: ./boot/init.sh
      - run: ./scripts/sync.sh --force
