name: Continuous Integration

on: [push]

jobs:
  build:
    runs-on: macos-10.14
    steps:
      - uses: actions/checkout@v1
      - name: Setup environment
        run: |
          brew list
          # Actions VMs already has brew installed, and we need to
          # unlink the existing node package first before we run setup
          brew unlink node@6
          ./boot/init.sh
      - name: Install dependencies
        run: |
          # Remove cask entries first
          cat Brewfile | grep -vE "cask " > Brewfile.alt
          mv Brewfile.alt Brewfile
          brew bundle
      - name: Run linters
        run: make check
      - name: Test linking and syncing
        run: ./scripts/sync.sh --force
