name: Main Workflow

on: [push]

jobs:
  test:
    runs-on: macos-10.15
    env:
      CI: true
    steps:
      - uses: actions/checkout@v1
  build:
    runs-on: macos-10.15
    env:
      CI: true
    steps:
      - uses: actions/checkout@v1
      - uses: cachix/install-nix-action@v13
        with:
          install_url: https://releases.nixos.org/nix/nix-2.3.15/install
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-build https://github.com/LnL7/nix-darwin/archive/master.tar.gz -A installer
      # - run: brew list
      # - run: ./boot/init.sh
