name: Main Workflow

on: [push]

jobs:
  test:
    runs-on: macos-10.15
    env:
      CI: true
    steps:
      - uses: actions/checkout@v1
  build:
    runs-on: macos-10.15
    env:
      CI: true
    steps:
      - uses: actions/checkout@v1
      # - run: brew list
      # - run: ./boot/init.sh
